[package]
name = "cen"
version = "0.0.2"
edition = "2021"
authors = ["Angelo Carly <angelo.carly@protonmail.com"]
description = "Vulkan window backend"
readme = "README.md"
repository = "https://github.com/angelocarly/cen"
license = "MIT"
keywords = ["vulkan", "render", "engine"]
categories = ["rendering::engine"]

[dependencies]
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"
winit = "0.29.15"
shaderc = "0.8.3"
log = "0.4.21"
env_logger = "0.11.5"
gpu-allocator = { version = "0.27.0" }
glam = "0.28.0"
bytemuck = { version = "1.17.0", features = ["derive"] }
notify = { version = "6.1.1" }
notify-debouncer-mini = "0.4.1"
slotmap = "1.0.7"